### ISSUE TITLE
How to disable internal debug message?

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#75] opened 2019-11-21 05:14 UTC
Hi, 
I often see a lot of debug message prompted from ROSE library.
such as,
`Error: problem this = 0x7fb1c2dcdc30 = SgClassDeclaration = xf_Mat_8_1080_1920_32_
Inside of Sg_File_Info::display(declarationAssociatedWithSymbol == NULL: debug) of this pointer = 0x7fb1bce5d270
     isTransformation                      = true (part of a transformation)
     isCompilerGenerated                   = false
     isOutputInCodeGeneration              = true (output in code generator)
     isShared                              = false
     isFrontendSpecific                    = false
     isSourcePositionUnavailableInFrontend = false
     isCommentOrDirective                  = false
     isToken                               = false
     isDefaultArgument                     = false
`

Thanks
-Sean

**Comment by charlesareynolds** [comment] 2020-01-22 00:44
Sean,

Do you have some example code that produces this output?

Charles

**Comment by charlesareynolds** [comment] 2020-04-21 20:14
Sean,

Are you still having this problem?

Charles

**Comment by chunhualiao** [comment] 2020-10-06 21:20
closing this since no reproducer for this issue.

**Closed by chunhualiao** 2020-10-06 21:20 UTC
