### ISSUE TITLE
ROSE crashes when dealing with two consecutive labels

### ISSUE THREAD

**Issue by gary-bai** [rose-compiler/rose#77] opened 2019-11-27 07:45 UTC
Example code:

    void k()
    {
        int x = 0;
        if (x) {
            goto a;
        }
        goto b;
    a:
    b:
        x += 1;
    }

AST dump around the labels:

    SgGotoStatement:goto a;
    SgGotoStatement:goto b;
    SgLabelStatement:a:b:x += 1;
    SgLabelStatement:b:x += 1;
    SgExprStatement:x += 1;
    SgPlusAssignOp:x += 1

Crash:

    created CFGNode with illegal index:
    index = 1 while max index is:0
    Error: node = 0x7f8c84e32010 = SgLabelStatement

    src/frontend/SageIII/virtualCFG/virtualCFG.C:40: 
    VirtualCFG::CFGNode::CFGNode(SgNode*, unsigned int): Assertion `false' failed.

    /lib64/libc.so.6(+0x36280)[0x7f8c91e98280]
    /lib64/libc.so.6(gsignal+0x37)[0x7f8c91e98207]
    /lib64/libc.so.6(abort+0x148)[0x7f8c91e998f8]
    /lib64/libc.so.6(+0x2f026)[0x7f8c91e91026]
    /lib64/libc.so.6(+0x2f0d2)[0x7f8c91e910d2]
    /rose/lib/librose.so.0(_ZN10VirtualCFG7CFGNodeC2EP6SgNodej+0x129)[0x7f8c9731f049]
    /rose/lib/librose.so.0(+0x20c5bd8)[0x7f8c97305bd8]
    /rose/lib/librose.so.0(_ZN15SgExprStatement11cfgOutEdgesEj+0x38)[0x7f8c9730a2d8]
    /rose/lib/librose.so.0(_ZNK10VirtualCFG7CFGNode8outEdgesEv+0x1b)[0x7f8c9731edeb]
    /rose/lib/librose.so.0(_ZNK10VirtualCFG15FilteredCFGNodeI11IsDFAFilterE8outEdgesEv+0x29)[0x7f8c972db4f9]
    /rose/lib/librose.so.0(+0x25b7a37)[0x7f8c977f7a37]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(+0x25b7aff)[0x7f8c977f7aff]
    /rose/lib/librose.so.0(_ZN16DefUseAnalysisPF3runEP20SgFunctionDefinitionRb+0x2c7)[0x7f8c977f8217]
    /rose/lib/librose.so.0(_ZN14DefUseAnalysis31start_traversal_of_one_functionEP20SgFunctionDefinition+0x222)[0x7f8c977ef722]

**Comment by pinnown** [comment] 2019-11-27 19:27
Are you using a rose tool or your own? What command line did you use to trigger this?

**Comment by gary-bai** [comment] 2019-11-28 01:47
The crash is triggered from our c++ compiler.

**Comment by seanchen1002** [comment] 2019-11-28 04:55
It is triggered by running defuse analysis

**Comment by mschordan** [comment] 2019-12-10 18:22
Thanks for reporting this issue and the very good test case. The bug was caused by a recent change in the ROSE AST. The bug has been fixed and is in the pipeline for being merged into master. Ticket ROSE-2381.

**Comment by mschordan** [comment] 2019-12-11 00:23
The bugfix is available in ROSE 0.9.12.42.

**Closed by mschordan** 2019-12-11 00:23 UTC
